version: "3.9"
networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.31.0.0/16
services:
  nodejs-20.3:
    image: node:20.3
    container_name: node-20.3
    tty: true
    volumes:
     - /workspaces/advanced-algorithms-course/src/node-js:/srv
    networks:
      default:
        ipv4_address: 172.31.0.2
  